const SET_STEPPER_DATA = 'SET_STEPPER_DATA';
const SET_STEPPER_RAW = 'SET_STEPPER_RAW';
const SET_STEPPER_CURRENT = 'SET_STEPPER_CURRENT';
const SET_STEPPER_OPTIONS = 'SET_STEPPER_OPTIONS';

export default {
  SET_STEPPER_DATA,
  SET_STEPPER_RAW,
  SET_STEPPER_CURRENT,
  SET_STEPPER_OPTIONS
};
